reaction_wheel:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  # Velocity Controllers ---------------------------------------
  # previous setting
  # reaction_wheel_front_velocity_controller:
  #   type: effort_controllers/JointVelocityController
  #   joint: reaction_wheel_front_joint
  #   pid: {p: 0.01, i: 0, d: 0}
  reaction_wheel_front_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: reaction_wheel_front_joint
    pid: {p: 0.01, i: 0, d: 0}
  reaction_wheel_back_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: reaction_wheel_back_joint
    pid: {p: 0.01, i: 0, d: 0}
  reaction_wheel_right_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: reaction_wheel_right_joint
    pid: {p: 0.01, i: 0, d: 0}
  reaction_wheel_left_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: reaction_wheel_left_joint
    pid: {p: 0.01, i: 0, d: 0}
  #tentacle position controller----------------------------------------------
  # previous setting
  # tentacle_right_link_1_joint_position_controller:
  #   type: effort_controllers/JointPositionController
  #   joint: tentacle_right_link_1_joint
  #   pid: {p: 0.1, i: 0, d: 0}
  tentacle_right_link_1_joint_position_controller:
    type: velocity_controllers/JointPositionController
    joint: tentacle_right_link_1_joint
    pid: {p: 0.05, i: 0, d: 0}
  tentacle_left_link_1_joint_position_controller:
    type: velocity_controllers/JointPositionController
    joint: tentacle_left_link_1_joint
    pid: {p: 0.05, i: 0, d: 0}
  tentacle_left_link_2_joint_position_controller:
    type: velocity_controllers/JointPositionController
    joint: tentacle_left_link_2_joint
    pid: {p: 0.05, i: 0, d: 0}
  tentacle_right_link_2_joint_position_controller:
    type: velocity_controllers/JointPositionController
    joint: tentacle_right_link_2_joint
    pid: {p: 0.05, i: 0, d: 0}
  tentacle_right_link_3_joint_position_controller:
    type: velocity_controllers/JointPositionController
    joint: tentacle_right_link_3_joint
    pid: {p: 0.05, i: 0, d: 0}
  tentacle_left_link_3_joint_position_controller:
    type: velocity_controllers/JointPositionController
    joint: tentacle_left_link_3_joint
    pid: {p: 0.05, i: 0, d: 0}
  tentacle_right_link_4_joint_position_controller:
    type: velocity_controllers/JointPositionController
    joint: tentacle_right_link_4_joint
    pid: {p: 0.05, i: 0, d: 0}
  tentacle_left_link_4_joint_position_controller:
    type: velocity_controllers/JointPositionController
    joint: tentacle_left_link_4_joint
    pid: {p: 0.05, i: 0, d: 0}
  tentacle_up_link_1_joint_position_controller:
    type: velocity_controllers/JointPositionController
    joint: tentacle_up_link_1_joint
    pid: {p: 0.05, i: 0, d: 0}
  tentacle_up_link_2_joint_position_controller:
    type: velocity_controllers/JointPositionController
    joint: tentacle_up_link_2_joint
    pid: {p: 0.05, i: 0, d: 0}
  tentacle_up_link_3_joint_position_controller:
    type: velocity_controllers/JointPositionController
    joint: tentacle_up_link_3_joint
    pid: {p: 0.05, i: 0, d: 0}
  tentacle_up_link_4_joint_position_controller:
    type: velocity_controllers/JointPositionController
    joint: tentacle_up_link_4_joint
    pid: {p: 0.05, i: 0, d: 0}
  tentacle_down_link_1_joint_position_controller:
    type: velocity_controllers/JointPositionController
    joint: tentacle_down_link_1_joint
    pid: {p: 0.05, i: 0, d: 0}
  tentacle_down_link_2_joint_position_controller:
    type: velocity_controllers/JointPositionController
    joint: tentacle_down_link_2_joint
    pid: {p: 0.05, i: 0, d: 0}
  tentacle_down_link_3_joint_position_controller:
    type: velocity_controllers/JointPositionController
    joint: tentacle_down_link_3_joint
    pid: {p: 0.05, i: 0, d: 0}
  tentacle_down_link_4_joint_position_controller:
    type: velocity_controllers/JointPositionController
    joint: tentacle_down_link_4_joint
    pid: {p: 0.05, i: 0, d: 0}